require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

RNFB_SCRIPT_PHASES = [
  '[CP-User] [RNFB] Core Configuration',
  '[CP-User] [RNFB] Crashlytics Configuration',
].freeze

def configure_rnfb_script_phases(installer)
  installer.aggregate_targets.each do |aggregate_target|
    project = aggregate_target.user_project
    next unless project

    updated = false

    project.targets.each do |target|
      next unless target.respond_to?(:shell_script_build_phases)

      target.shell_script_build_phases.each do |phase|
        next unless RNFB_SCRIPT_PHASES.include?(phase.name)

        phase.always_out_of_date = '1'
        updated = true
      end
    end

    project.save if updated
  end
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ios_deployment_target = podfile_properties['ios.deploymentTarget'] || '15.1'
platform :ios, ios_deployment_target

def set_xcconfig_build_setting(path, key, value)
  return unless path && File.exist?(path)

  contents = File.read(path)
  setting = "#{key} = #{value}"

  updated_contents =
    if contents.match?(/^#{Regexp.escape(key)}\s*=/)
      contents.gsub(/^#{Regexp.escape(key)}\s*=.*$/, setting)
    else
      "#{setting}\n#{contents}"
    end

  File.write(path, updated_contents) if updated_contents != contents
end

def configure_fmt_for_xcode_26(installer)
  fmt_target = installer.pods_project.targets.find { |target| target.name == 'fmt' }
  return unless fmt_target

  fmt_target.build_configurations.each do |config|
    config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
    set_xcconfig_build_setting(
      config.base_configuration_reference&.real_path,
      'CLANG_CXX_LANGUAGE_STANDARD',
      'c++17'
    )
  end
end

def normalize_pods_deployment_target(installer, deployment_target)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end
  end
end

prepare_react_native_project!

target 'app' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    configure_fmt_for_xcode_26(installer)
    normalize_pods_deployment_target(installer, ios_deployment_target)
  end
end

post_integrate do |installer|
  configure_rnfb_script_phases(installer)
end
